# [[main]]
#  name = "Home"
#  url = ""
#  weight = -110


[[main]]
  name = "Over"
  identifier = "Over"
  weight = -107
[[main]]
  parent = "Over"
  name = "Over"
  url = "0_community/about/"
  weight = -107
  [[main]]
  parent = "Over"
  name = "Bestuur"
  url = "0_community/bestuur/"
  weight = -106
  [[main]]
  parent = "Over"
  name = "OSGeo Internationaal"
  url = "0_community/internationaal/"
  weight = -105
[[main]]
  parent = "Over"
  name = "Geoforum.nl"
  url = "0_community/geoforum-nl/"
  weight = -98
[[main]]
  parent = "Over"
  name = "Wiki"
  url = "0_community/wiki/"
  weight = -96
[[main]]
  parent = "Over"
  name = "Community"
  url = "0_community/community/"
  weight = -96


[[main]]
  name = "Events"
  identifier = "Events"
  weight = -106
[[main]]
  parent = "Events"
  name = "Agenda &neArr;"
  url = "https://www.meetup.com/osgeonl/"
  weight = -99
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2024 &neArr;"
  url = "https://foss4g.nl/"
  weight = -97  
[[main]]
  parent = "Events"
  name = "PostGIS dag &neArr;"
  url = "https://postgisdag.nl/"
  weight = -97  
[[main]]
  parent = "Events"
  name = "De Grote Geo Show  &neArr;"
  url = "https://tv.osgeo.nl/"
  weight = -90

[[main]]
  parent = "Events"
  name = "Afgelopen events"
   weight = -80
 [[main]]
  parent = "Afgelopen events"
  name = "FOSS4GNL 2023 &neArr;"
  url = "https://2023.foss4g.nl/"
  weight = -97  
[[main]]
  parent = "Afgelopen events"
  name = "FOSS4GNL 2021 &neArr;"
  url = "https://2021foss4g.nl/"
  weight = -96
[[main]]
  parent = "Afgelopen events"
  name = "FOSS4GNL 2019 &neArr;"
  url = "https://2019.foss4g.nl/"
  weight = -95
[[main]]
  parent = "Afgelopen events"
  name = "FOSS4GNL 2018 &neArr;"
  url = "https://2018.foss4g.nl/"
  weight = -94
[[main]]
  parent = "Afgelopen events"
  name = "FOSS4GNL 2017 &neArr;"
  url = "https://2017.foss4g.nl/"
  weight = -93
[[main]]
  parent = "Afgelopen events"
  name = "QGIS Gebruikersdag 2018 &neArr;"
  url = "http://www.qgis.nl/2018/01/22/programma-gebruikersmiddag-compleet/"
  weight = -92
[[main]]
  parent = "Afgelopen events"
  name = "GRASS GIS crash course"
  url = "0_events/grassgis-course/"
  weight = -91
[[main]]
  parent = "Afgelopen events"
  name = "OSGeo.nl Dag 2017"
  url = "0_events/dag/"
  weight = -90

[[main]]
  name = "Nieuws"
  identifier = "Nieuws"
  url = "posts/"
  weight = -106

[[main]]
  name = "Sponsors"
  identifier = "Sponsors"
  weight = -106
[[main]]
  parent = "Sponsors"
  name = "Huidige Sponsors"
  url = "0_sponsors/sponsors/"
  weight = -90
[[main]]
  parent = "Sponsors"
  name = "Sponsorplan"
  url = "0_sponsors/sponsorplan/"
  weight = -89

[[main]]
  name = "Contact"
  url = "0_contact/"
  weight = -105

# social menu links
[[social]]
  name = "mail"
  weight = 1
  url = "mailto:info@osgeo.nl"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/osgeonl"
[[social]]
  name = "youtube"
  type = "social"
  weight = 3
  url = "https://www.youtube.com/channel/UCvSAN6ur4RoGUqxtvmgsb8g"
[[social]]
  name = "github"
  type = "social"
  weight = 4
  url = "https://github.com/osgeonl"