# [[main]]
#  name = "Home"
#  url = ""
#  weight = -110

[[main]]
  name = "Thuis"
  url = "/"
  weight = -111

[[main]]
  name = "Over"
  url = "over-ons/"
  weight = -110

[[main]]
  name = "Meedoen"
  url = "meedoen/"
  weight = -109

[[main]]
  name = "Events"
  identifier = "Events"
  # url = "events/"
  weight = -108
[[main]]
  parent = "Events"
  name = "Overzicht"
  url = "events/"
  weight = -99
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2021"
  # url = "writings/blog/"
  url = "https://foss4g.nl/"
  weight = -98
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2019"
  url = "https://2019.foss4g.nl/"
  weight = -97
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2018"
  url = "https://2018.foss4g.nl/"
  weight = -96
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2017"
  url = "https://2017.foss4g.nl/"
  weight = -95
[[main]]
  parent = "Events"
  name = "QGIS Gebruikersdag 2018"
  url = "http://www.qgis.nl/2018/01/22/programma-gebruikersmiddag-compleet/"
  weight = -94
[[main]]
  parent = "Events"
  name = "GRASS GIS crash course"
  url = "grassgis-course/"
  weight = -93
[[main]]
  parent = "Events"
  name = "OSGeo.nl Dag 2017"
  url = "dag/"
  weight = -92

[[main]]
  name = "Nieuws"
  identifier = "Nieuws"
  url = "nieuws/"
  weight = -107

[[main]]
  name = "Agenda"
  identifier = "Agenda"
  url = "agenda/"
  weight = -106

[[main]]
  name = "Community"
  identifier = "Community"
  # url = "community/"
  weight = -105
[[main]]
  parent = "Community"
  name = "Overzicht"
  url = "community/"
  weight = -99
[[main]]
  parent = "Community"
  name = "Geoforum.nl"
  url = "geoforum-nl/"
  weight = -98
[[main]]
  parent = "Community"
  name = "Leer!"
  url = "community/leer/"
  weight = -97
[[main]]
  parent = "Community"
  name = "Wiki"
  url = "wiki/"
  weight = -96
[[main]]
  parent = "Community"
  name = "Blogs"
  url = "blog/"
  weight = -95
[[main]]
  parent = "Community"
  name = "Aanbieders"
  url = "aanbieders/"
  weight = -94
[[main]]
  parent = "Community"
  name = "Verslagen"
  url = "verslagen/"
  weight = -93
[[main]]
  parent = "Community"
  identifier = "geoNetwork-gebruikersGroep"
  name = "GeoNetwork GebruikersGroep"
  # url = "verslagen/"
  weight = -92
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  name = "Overzicht"
  # url = "overzicht/"
  url = "geonetwork-gebruikersgroep/"
  weight = -99
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  name = "Best practices"
  # url = "geonetwork-gebruikersgroep/best-practices/"
  url = "best-practices/"
  weight = -98
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  name = "Documentatie"
  # url = "geonetwork-gebruikersgroep/documentatie/"
  url = "documentatie/"
  weight = -97
[[main]]
  parent = "Community"
  name = "QGIS Gebruikersgroep"
  url = "https://qgis.nl/"
  weight = -91

[[main]]
  name = "Sponsors"
  url = "sponsors/"
  weight = -104

[[main]]
  name = "Contact"
  url = "contact/"
  weight = -103

# [[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -106

# Submenus are done this way: parent -> identifier
# [[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -105
# [[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
# [[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

# social menu links

[[social]]
  name = "linkedin"
  weight = 1
  url = "http://www.linkedin.com/in/justb4"
[[social]]
  name = "twitter"
  weight = 2
  url = "http://twitter.com/justb4"
[[social]]
  name = "github"
  type = "social"
  weight = 3
  url = "https://github.com/justb4"
[[social]]
  name = "rss"
  url = "http://justobjects.nl/feed/"
  weight = 4

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
