# [[main]]
#  name = "Home"
#  url = ""
#  weight = -110

[[main]]
  name = "Thuis"
  url = "/"
  weight = -111


[[main]]
  name = "Community"
  identifier = "Community"
  # url = "community/"
  weight = -109
[[main]]
  parent = "Community"
  name = "Over"
  url = "over-ons/"
  weight = -107
[[main]]
  parent = "Community"
  identifier = "Community-Meedoen"
  name = "Sluit je aan!"
  url = "meedoen/"
  weight = -106
[[main]]
  parent = "Community"
  name = "Geoforum.nl"
  url = "geoforum-nl/"
  weight = -98
[[main]]
  parent = "Community"
  name = "Leer!"
  # url = "community/leer/"
  url = "categories/educatief/"
  weight = -97
[[main]]
  parent = "Community"
  name = "Wiki"
  url = "wiki/"
  weight = -96
[[main]]
  parent = "Community"
  name = "Blogs"
  url = "blog/"
  weight = -95
[[main]]
  parent = "Community"
  name = "Aanbieders"
  url = "aanbieders/"
  weight = -94
[[main]]
  parent = "Community"
  name = "Verslagen"
  # url = "verslagen/"
  url = "categories/verslag/"
  weight = -93
[[main]]
  parent = "Community"
  identifier = "geoNetwork-gebruikersGroep"
  name = "GeoNetwork GebruikersGroep &#8227;"
  # url = "verslagen/"
  weight = -92
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  identifier = "GeoNetwork-Overzicht"
  name = "Overzicht"
  # url = "overzicht/"
  url = "geonetwork-gebruikersgroep/"
  weight = -99
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  name = "Best practices"
  # url = "geonetwork-gebruikersgroep/best-practices/"
  url = "best-practices/"
  weight = -98
[[main]]
  parent = "geoNetwork-gebruikersGroep"
  name = "Documentatie"
  # url = "geonetwork-gebruikersgroep/documentatie/"
  url = "documentatie/"
  weight = -97
[[main]]
  parent = "Community"
  name = "QGIS Gebruikersgroep &neArr;"
  url = "https://qgis.nl/"
  weight = -91

[[main]]
  name = "Events"
  identifier = "Events"
  # url = "events/"
  weight = -108
[[main]]
  parent = "Events"
  name = "Agenda &neArr;"
  url = "https://www.meetup.com/osgeonl/"
  weight = -99
[[main]]
  parent = "Events"
  identifier = "Events-Overzicht"
  name = "Overzicht"
  # url = "events/"
  url = "categories/event/"
  weight = -98
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2021 &neArr;"
  # url = "writings/blog/"
  url = "https://foss4g.nl/"
  weight = -97
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2019 &neArr;"
  url = "https://2019.foss4g.nl/"
  weight = -96
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2018 &neArr;"
  url = "https://2018.foss4g.nl/"
  weight = -95
[[main]]
  parent = "Events"
  name = "FOSS4GNL 2017 &neArr;"
  url = "https://2017.foss4g.nl/"
  weight = -94
[[main]]
  parent = "Events"
  name = "QGIS Gebruikersdag 2018 &neArr;"
  url = "http://www.qgis.nl/2018/01/22/programma-gebruikersmiddag-compleet/"
  weight = -93
[[main]]
  parent = "Events"
  name = "GRASS GIS crash course"
  url = "grassgis-course/"
  weight = -92
[[main]]
  parent = "Events"
  name = "OSGeo.nl Dag 2017"
  url = "dag/"
  weight = -91

[[main]]
  name = "Nieuws"
  identifier = "Nieuws"
  # url = "nieuws/"
  # url = "category/nieuws/"
  url = "categories/nieuws/"
  weight = -107


[[main]]
  name = "Sponsors"
  url = "sponsors/"
  weight = -104

[[main]]
  name = "Contact"
  url = "contact/"
  weight = -103

# social menu links

[[social]]
  name = "mail"
  weight = 1
  url = "mailto:info@osgeo.nl"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/osgeonl"
[[social]]
  name = "youtube"
  type = "social"
  weight = 3
  url = "https://www.youtube.com/channel/UCvSAN6ur4RoGUqxtvmgsb8g"
[[social]]
  name = "github"
  type = "social"
  weight = 4
  url = "https://github.com/osgeonl"
#[[social]]
#  name = "flickr"
#  type = "social"
#  weight = 3
#  url = "https://www.flickr.com/groups/osgeonl"
#[[social]]
#  name = "rss"
#  url = "http://osgeo.nl/feed/"
#  weight = 4

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
